- hosts: masters
  become: yes
  tasks:
    - name: Start the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster.txt
      args:
        chdir: $HOME
        creates: cluster.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
      delegate_to: localhost

    - name: copy admin.conf to user's kube config
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube
        owner: ubuntu

    - name: Move kube config file
      shell: cp /home/ubuntu/.kube/master/etc/kubernetes/admin.conf /home/ubuntu/.kube/config
      delegate_to: localhost

    - name: Delete master folder
      file:
          path: /home/ubuntu/.kube/master
          state: absent
      delegate_to: localhost

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_seltup.txt
      args:
        chdir: $HOME
        creates: pod_setup.txt
      delegate_to: localhost
